#!/bin/bash
## test home
testdir=$(cd $(dirname $0)/; pwd)
## word home
workdir=$(dirname $testdir)
cd $workdir

module=anteye
app=tycs-$module
pidfile=var/app.pid
logfile=var/app.log
control=./control
httpprex="127.0.0.1:8001"

## statistics
function counter(){
    curl -s "$httpprex/counter/all" | python -m json.tool
}

## config
function config(){
    action=$1
    case $action in
        "reload")
            curl -s "$httpprex/config/reload" | python -m json.tool
            ;;
        *)
            curl -s "$httpprex/config" | python -m json.tool
            ;;
    esac
}

## build
function build(){
    $control build
}
function start(){
    $control start
}
function stop(){
    $control stop
}

## tail
function tail_log(){
    $control tail
}

action=$1
case $action in
    "build")
        build
        ;;
    "start")
        start
        ;;
    "stop")
        stop
        ;;
    "restart")
        stop && build && start
        ;;
    "config")
        config $2
        ;;
    "tail")
        tail_log
        ;;
    *)
        counter
        ;;
esac

